apiVersion: secrets.infisical.com/v1alpha1
kind: InfisicalSecret
metadata:
  name: msp-infisical-secret
  namespace: akhil-test
spec:
  hostAPI: https://app.infisical.com/api
  resyncInterval: 60
  authentication:
    serviceAccount:
      serviceAccountRef:
        name: msp-workload-sa
        namespace: akhil-test
  managedSecretReference:
    secretName: msp-infisical-secrets
    secretNamespace: akhil-test
    creationPolicy: Owner
  secrets:
    - secretPath: /
      projectId: msp-platform
      environment: prod
      secretsToSync:
        - secretKey: oauth2.client-id
          remoteKey: oauth2.client-id
        - secretKey: oauth2.client-secret
          remoteKey: oauth2.client-secret
        - secretKey: db.url
          remoteKey: db.url
        - secretKey: db.username
          remoteKey: db.username
        - secretKey: db.password
          remoteKey: db.password
        - secretKey: rabbitmq.host
          remoteKey: rabbitmq.host
        - secretKey: rabbitmq.username
          remoteKey: rabbitmq.username
        - secretKey: rabbitmq.password
          remoteKey: rabbitmq.password
        - secretKey: minio.access-key
          remoteKey: minio.access-key
        - secretKey: minio.secret-key
          remoteKey: minio.secret-key
        - secretKey: n8n.encryption-key
          remoteKey: n8n.encryption-key