apiVersion: v1
kind: ServiceAccount
metadata:
  name: msp-workload-sa
  namespace: akhil-test
  annotations:
    # AWS IRSA (IAM Roles for Service Accounts)
    eks.amazonaws.com/role-arn: arn:aws:iam::258397330626:role/dev-integration-role
    # GCP Workload Identity (if migrating to GKE)
    # iam.gke.io/gcp-service-account: msp-workload@PROJECT_ID.iam.gserviceaccount.com
  labels:
    app: msp-platform
    component: workload-identity