apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: cp-service
  namespace: akhil-test
  labels:
    app: cp-service
    part-of: msp-platform
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/minScale: "0"
        autoscaling.knative.dev/maxScale: "5"
    spec:
      containerConcurrency: 10
      timeoutSeconds: 120
      serviceAccountName: msp-workload-sa
      containers:
        - name: cp-service
          image: 258397330626.dkr.ecr.us-east-1.amazonaws.com/cp-service:latest
          ports:
            - containerPort: 8080
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 15
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
            initialDelaySeconds: 20
            periodSeconds: 10
            failureThreshold: 3
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: "prod"
          resources:
            requests:
              cpu: "250m"
              memory: "512Mi"
            limits:
              cpu: "1000m"
              memory: "1024Mi"